[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "laravel-mix-django"
authors = [{name = "Alex", email = "alex@github"}]
dynamic = ["version", "description"]
